Added a new dropdown at navbar and details page
GVR-Secure-Solutions/lekkalu-frontend pull request #380
Opened 2023-12-11 17:34 UTC by imhardikdesai

I have added dropdown in navbar for features/tools #357 
 
![image](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/87645745/b13614a9-42b1-4646-bb6d-41b873782dab)

And also added details page for this

2023-12-11 18:06 UTC, mohitkhatri06 commented
@imhardikdesai when I scroll in any feature and then try to go to other feature it starts from the bottom

2023-12-12 15:07 UTC, rockingrohit9639 requested changes

2023-12-12 15:07 UTC, rockingrohit9639 commented on src/components/UnAuthenticatedHeader/UnAuthenticatedHeader.tsx
>    React.ElementRef<'a'>,
why do we need `forwardRef` here ?

2023-12-12 15:45 UTC, imhardikdesai commented
@mohitkhatri06 @rockingrohit9639 i will fix the changes

2023-12-15 10:11 UTC, imhardikdesai commented
Hello @mohitkhatri06 and @rockingrohit9639 Please review above changes and let me now if anything else

2023-12-20 18:39 UTC, mohitkhatri06 commented on src/pages/Features/FeaturesDetails.tsx
> +      break
@imhardikdesai can you have a look on this file?

2023-12-21 02:32 UTC, imhardikdesai commented on src/pages/Features/FeaturesDetails.tsx
> +      break
Yes @mohitkhatri06 I have wrapped logic inside useMemo hook as Rohit says

2023-12-21 02:33 UTC, imhardikdesai commented on src/pages/Features/FeaturesDetails.tsx
> +      break
Do you think I have to define route for each components in App.js??

2023-12-21 12:47 UTC, mohitkhatri06 commented on src/pages/Features/FeaturesDetails.tsx
> +      break
@rockingrohit9639 what do you think, i guess we can proceed now?

2023-12-23 07:02 UTC, mohitkhatri06 approved these changes

2023-12-24 08:54 UTC, rockingrohit9639 submitted a review, later dismissed
He has not updated what I have said but @mohitkhatri06 wanted me to approve it so I here I am.

2024-01-02 17:26 UTC, rockingrohit9639 approved these changes

2024-01-02 17:28 UTC, merged