Expense (Search Bar, Multiple Tags)
GVR-Secure-Solutions/lekkalu-frontend pull request #413
Opened 2024-01-11 17:05 UTC by imhardikdesai

- Added Search Bar For Expense Search
![image](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/87645745/a7b60fc0-3840-4421-98d8-9566cc30763a)

- User can add multiple Tags and also create new tag when they add or update expense
![image](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/87645745/e6a9ddcb-9f8c-49c9-8368-ba27be815ab6)
![image](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/87645745/43ee6d6f-0b02-4481-8389-014bd55639a4)

## Close these issues
#194 #401

2024-01-14 17:49 UTC, mohitkhatri06 commented
as discussed with developer, we need to show correct page number in search results

2024-01-16 17:23 UTC, imhardikdesai commented
@mohitkhatri06 
#### Completed Following Changes
- Remove `TagInput.jsx` File
- Add Lucide Search Icon
- Reduce width of search bar
- Set correct page number in search results

2024-01-16 17:45 UTC, bharathkumarchowdary approved these changes

2024-01-16 17:46 UTC, bharathkumarchowdary requested changes
let's wait for Mohit's approval

2024-01-16 19:48 UTC, bharathkumarchowdary approved these changes

2024-01-20 12:41 UTC, merged