Profile details update functionality
GVR-Secure-Solutions/lekkalu-frontend pull request #429
Opened 2024-01-28 05:56 UTC by nanipunepalle

2024-01-31 17:02 UTC, nanipunepalle commented on src/queries/user.ts
> +  const { data } = await userClient.put<any>('/users/detail', dto, { headers })
@mohitkhatri06  I didn't get what you suggested, env file is updated so I have given /users/detail here

2024-02-03 05:16 UTC, mohitkhatri06 approved these changes

2024-02-03 06:08 UTC, bharathkumarchowdary requested changes
- [ ] Please include one unit test for the functionality you introduced
- [ ] Also mask the reset password block in user section such that whenever someone introduces reset password, will just enable it again

2024-02-03 18:59 UTC, mohitkhatri06 approved these changes

2024-02-05 18:04 UTC, mohitkhatri06 approved these changes

2024-02-07 02:05 UTC, bharathkumarchowdary requested changes
Please move user data download button to user profile. And make user understand the purpose of the button

2024-02-11 14:18 UTC, mohitkhatri06 approved these changes

2024-02-17 10:36 UTC, bharathkumarchowdary approved these changes

2024-02-18 06:25 UTC, mohitkhatri06 commented
https://github.com/GVR-Secure-Solutions/lekkalu-frontend/pull/449

2024-02-18 06:25 UTC, closed without merging