feat: :sparkles: redesign existing charts with apex-charts 📊
GVR-Secure-Solutions/lekkalu-frontend pull request #487
Opened 2024-03-16 08:33 UTC by imhardikdesai

Balance Sheet Page charts
- <img width="1279" alt="image" src="https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/87645745/eecd2fdc-0449-4a32-879c-24b326d4a62e">

Lending Page Charts
- <img width="1276" alt="image" src="https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/87645745/06ab9d90-d495-4d3d-bb41-b2ce7219d50b">

Expense Page Charts
- <img width="1274" alt="image" src="https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/87645745/83b3e5b6-0d10-4ab8-9ff4-42bb9e12364b">

2024-03-19 17:58 UTC, bharathkumarchowdary requested changes
Please make budgets scrollable
chart borders are clear in epxenses but not present in balance sheet charts
we don't need Liability bar chart in balance sheet

2024-03-30 04:44 UTC, imhardikdesai commented
Hello @bharathkumarchowdary @mohitkhatri06 please review new changes

2024-04-01 17:37 UTC, mohitkhatri06 approved these changes

2024-04-01 17:41 UTC, mohitkhatri06 approved these changes

2024-04-02 01:43 UTC, bharathkumarchowdary approved these changes

2024-04-02 01:43 UTC, bharathkumarchowdary requested changes
tests are failing

2024-04-04 03:47 UTC, bharathkumarchowdary approved these changes

2024-04-04 03:47 UTC, merged