Show all scenarios in comparison graph.
GVR-Secure-Solutions/lekkalu-frontend pull request #517
Opened 2024-04-10 14:27 UTC by Sandip-Z

This PR fixes all scenarios not displaying in graph issue.
Related to issue #515.

2024-04-10 17:15 UTC, bharathkumarchowdary requested changes
- I'm seeing a lot of failures in network tab 
![image](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/8872935/6b2c156a-8108-49aa-ac84-555f4e0faf56)
- Chart doesn't look appealing. use some other COTS library like apex charts
- I feel simulate button's position is not eye-catching for most visitors. @mohitkhatri06  can comment
- We need a copy button upon pressing which it will 
- ask for signup/login if a visitor and redirect to the same comparison created for his profile
- if a signed in user, then redirect to create comparison with all same
- Setting a comparison to public/private should be a single click with an icon
- Let's imporove overall look, and feel of comparison feature

2024-04-11 11:47 UTC, Sandip-Z commented
@bharathkumarchowdary lets come up with a design, meanwhile i will work on copy feature (point no. 4).

2024-04-11 12:48 UTC, bharathkumarchowdary commented
all other items are being solved in a new issue
let's approve and merge this bugfix @mohitkhatri06

2024-04-11 12:48 UTC, bharathkumarchowdary approved these changes

2024-04-11 12:49 UTC, merged