Support typescript
GVR-Secure-Solutions/lekkalu-frontend pull request #60
Opened 2023-05-31 10:28 UTC by jerncomania28

- Added Typescript support .
- Converted EMI Calculator components to use typescript.
- migrated EMI stylings to tailwindcss.
-  implemented a sample of a reusable way to make API Request leveraging react-query.

2023-05-31 18:43 UTC, mohitkhatri06 commented
as for now in UI getting these errors
![image](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/78607953/02a2a75b-db50-43f7-8a43-14693b65b054)

2023-06-01 03:28 UTC, bharathkumarchowdary commented
> as for now in UI getting these errors
> ![image](https://user-images.githubusercontent.com/78607953/242375886-02a2a75b-db50-43f7-8a43-14693b65b054.png)

@jerncomania28 , Do you too see the same error?
I remember you said there is a way to partially introduce typescript to project
If that is valid, I think you can introduce it to the parts you can solve for now.. no rush!

2023-06-01 13:31 UTC, jerncomania28 commented
I Don't  happen to encounter any of the errors and from what I'm seeing , it's the way you're going about The conversion , i modified the tsconfig to recognize react and accommodate javascript without type-checking , this is a typing errors , observe how I convert the files and use typing refer to index.tsx in the EMI_Calculator folder under pages and the FormInput component for reference .

Also , because the charts is leveraging a library you might have to install it's accompanying types usually something like @types/name-of-library

2023-06-01 16:44 UTC, bharathkumarchowdary commented
> I Don't happen to encounter any of the errors and from what I'm seeing , it's the way you're going about The conversion , i modified the tsconfig to recognize react and accommodate javascript without type-checking , this is a typing errors , observe how I convert the files and use typing refer to index.tsx in the EMI_Calculator folder under pages and the FormInput component for reference .
> 
> Also , because the charts is leveraging a library you might have to install it's accompanying types usually something like @types/name-of-library

@mohitkhatri06 , do we have any typing package for the charts as @jerncomania28 is suggesting?
@jerncomania28 , 

- I too see some errors in local env after checking out this branch. Uploaded to dropbox [here](https://www.dropbox.com/s/d2l8jt894ukac74/support_typescript_errors.pdf?dl=0)
- The build for this branch is failing, can you see what is the reason?

2023-06-02 06:13 UTC, mohitkhatri06 commented
@bharathkumarchowdary the file in which you mentioned the error at dropbox is module not found, we need to run 'npm install' as there are some package added into the project, and that needs to be added into your node_modules local folder.

For charts there is a package https://www.npmjs.com/package/@types/recharts as mentioned by @jerncomania28 , but the errors which are there is for all the components Support, Expenses etc.

2023-06-11 11:55 UTC, mohitkhatri06 commented
@bharathkumarchowdary when we click on the notification bell all notifications are visible but to close this, should we have concept where we can close that notification by clicking anywhere on the screen? as for now we need to click again on that bell icon.

2023-06-11 16:55 UTC, bharathkumarchowdary commented
> @bharathkumarchowdary when we click on the notification bell all notifications are visible but to close this, should we have concept where we can close that notification by clicking anywhere on the screen? as for now we need to click again on that bell icon.

Yes @mohitkhatri06 , @jerncomania28 ,
Clicking anywhere else should close that modal
I think this behaviour is also expected of the feedback button. Maybe @jerncomania28 can inherit that behaviour from it

2023-06-22 18:01 UTC, mohitkhatri06 commented on src/pages/EmiCalculator/index.tsx
> +    // setIsLoading(true);
@jerncomania28  as you commented these line it will not break other parts of it right?

2023-06-22 18:26 UTC, mohitkhatri06 commented
getting this error.
![image](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/78607953/b1b10367-64f8-4f86-94d8-9c82d90b7632)

2023-07-05 16:50 UTC, bharathkumarchowdary commented
but still the tests failed

2023-07-22 09:14 UTC, bharathkumarchowdary submitted a review, later dismissed

2023-07-24 06:10 UTC, mohitkhatri06 commented
getting following error in the sign up page also

https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/78607953/769b9581-08fe-4e45-9177-3563684d5d7c

2023-07-24 17:49 UTC, ivangarcilazo requested changes
Hi Jeremiah, I get these errors: In expenses the fetchTags error and the income statement error are not loading the data.
![Jeremiah](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/105944413/bfbbf39a-0983-417e-8cbf-bb91fe3f8cc8)
![Jeremiah 2](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/105944413/ebfb52bb-eb1f-4a9a-bd37-63998d526e99)

2023-07-29 16:48 UTC, bharathkumarchowdary commented
@ivangarcilazo , @mohitkhatri06 , do you have further comments on this PR?

2023-08-05 06:13 UTC, mohitkhatri06 commented
when trying to add new expense, the following error comes up. 
![image](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/78607953/ce130b17-b31b-493b-9f13-51f4427ce445)

and the expense table is not  visible.

2023-09-06 17:29 UTC, closed without merging